# Go live, uncomment this before push to github
backend:
  name: github
  repo: phuhh98/phuhh98.github.io
  branch: main
  base_url: https://netlify-cms-github-oauth-provider-o2ex.onrender.com
  squash_merges: true

# # config for local development, comment this before push to github
# backend:
#   name: proxy
#   proxy_url: http://localhost:8081/api/v1
#   branch: main # optional, defaults to master
#   squash_merges: true
# local_backend: true # to work with local git, comment this before push
# # end local dev block

publish_mode: editorial_workflow # https://decapcms.org/docs/editorial-workflows/
media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media

# # Ref https://decapcms.org/docs/cloudinary/
# media_library:
#   name: cloudinary
#   output_filename_only: false
#   config:
#     cloud_name: dchinnmfc
#     api_key: 693835254646836

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: mdx
    format: yaml-frontmatter
    slug: "{{year}}-{{month}}-{{slug}}"
    preview_path: blog/{{slug}}
    fields: # The fields for each document, usually in frontmatter
      - label: Title
        name: title
        widget: string

      - label: Description
        name: description
        widget: string

      - label: Publish Date
        name: pubDate
        widget: datetime

      - label: Hero image
        name: heroImage
        widget: image

      - label: Card image
        name: cardImage
        widget: image

      - label: Peek image
        name: peekImage
        widget: image

      - label: Category
        name: category
        widget: relation
        collection: "category"
        search_fields: ["name"]
        value_field: "name"

      - label: Tags
        name: tags
        widget: relation
        collection: "tag"
        search_fields: ["name"]
        value_field: "name"
        multiple: true
        min: 1

      - label: Body
        name: body
        widget: markdown

  - name: "category"
    label: "Category"
    folder: src/content/category
    create: true
    identifier_field: name
    extension: yaml
    format: yaml
    fields:
      - label: "Name"
        name: "name"
        widget: string

  - name: "tag"
    label: "Tag"
    folder: src/content/tag
    create: true
    identifier_field: name
    extension: yaml
    format: yaml
    fields:
      - label: "Name"
        name: "name"
        widget: string
